### ISSUE TITLE
Question: Error when trying to use the module in jest

### ISSUE THREAD

**Issue by kenfdev** [planetscale/database-js#68]
## Expected Behavior
"@planetscale/database" should be able to import in Jest tests.

## Current Behavior
An error occurs and jest is not able to run.

```
 FAIL  ./test.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /foo/node_modules/@planetscale/database/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { format } from './sanitization.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

## What I've tried
I'm not sure what the root cause is but it seems Jest cannot transform the ESM(?) file included in `@planetscale/database/dist/index.js`.

I assumed this error is a well-known jest misconfiguration and tried some of these solutions:

- support esm in `ts-node`
  - https://kulshekhar.github.io/ts-jest/docs/guides/esm-support/
- tried the same settings as this repository([planetscale/database-js](https://github.com/planetscale/database-js))

The same error occurred each time.

## Steps to Reproduce

I've created a minimum code base as follows:
https://github.com/kenfdev/planetscale-jest-poc

You can reproduce it with `npm test`.

I might totally be missing something from the beginning but am pretty much stuck right now. Any advice would be highly appreciated!
Thank you in advance!

**Comment by dgraham** [comment]
The reproduction link points to this repository. Do you have a minimal sample we can look at? Jest and Babel are capable of using JS modules, and it's usually a matter of configuring them to do the right thing.

**Comment by kenfdev** [comment]
@dgraham
Thanks for the response and apologies about the wrong link...
I've fixed the URL!
I also think it's a matter of jest configuration but transforming the module didn't seem to work 🤔 

I'll give it another try today!

**Comment by kenfdev** [comment]
@dgraham 
I've got it working and it actually was a misconfiguration of Jest. I needed to add `transformIgnorePatterns` to the settings.

```
transformIgnorePatterns: ["/node_modules/(?!@planetscale)"],
```

 I don't have much knowledge in this area, but I wonder if this could be improved. So everybody could use this library with jest out of the box.

**Comment by iheanyi** [comment]
This is more of a jest configuration problem than a package one, I believe. We'll look into it but for now we'll close this out since you've figured it out.

**Comment by tokenhousetopdev** [comment]
Also running into this issue and using the ignore pattern doesn't help with esbuild-jest

**Comment by tokenhousetopdev** [comment]
Literally using the poc repo still reproduces this. Can this be reopened I have been strugglign with this for a while ;(
